### ISSUE TITLE
Support HTTP Basic Authentication

### ISSUE THREAD

**Issue by psy-q** [fxposter/jsonrpc-client#11]
It would be nice if jsonrpc-client supported [HTTP Basic Authentication](http://www.ietf.org/rfc/rfc2617.txt). I have to use it to access an API and I so far haven't managed to monkey-patch around it.

Faraday supports it, e.g.:

```ruby
conn = Faraday.new(:url => 'https://kanboard.example.com') do |faraday|
    faraday.basic_auth(ENV['user'], ENV['pw']) # user/pass to get through basic auth
    faraday.adapter Faraday.default_adapter    # make requests with Net::HTTP
end
```
Taken from the [Kanboard API samples](https://kanboard.net/documentation/api-examples).

**Comment by fxposter** [comment]
Can you, please, read https://github.com/fxposter/jsonrpc-client/pull/2 first? :)

**Comment by psy-q** [comment]
Crap, I only looked at the existing issues but not the PRs :(  Ignore, please.

**Comment by psy-q** [comment]
Sorry to get back on this, but maybe this could be documented in the README? Should I try to write something and do a PR?

**Comment by fxposter** [comment]
This would be quite useful, cause I don't actively use/maintain this gem
currently!

12 Апр 2017 г. 5:45 PM пользователь "Psy-Q" <notifications@github.com>
написал:
